spring:
  application:
    name: jiang-service-admin
  boot:
    admin:
      client:
        url: http://34.80.214.44:8084
  zipkin:
    base-url: http://34.80.214.44:9411
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/jiang-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://34.80.214.44:8761/eureka/,http://34.80.214.44:8861/eureka/,http://34.80.214.44:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

mybatis:
  type-aliases-package: cn.jiang.station.platform.common.domain
  mapper-locations: classpath:mapper/*.xml