spring:
  application:
    name: jiang-admin
  zipkin:
    base-url: http://104.199.166.17:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://104.199.166.17:8761/eureka/,http://104.199.166.17:8861/eureka/,http://104.199.166.17:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info