spring:
  application:
    name: jiang-admin
  zipkin:
    base-url: http://35.241.113.30:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://35.241.113.30:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info