spring:
  application:
    name: jiang-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client: # false为单机版，true为集群版
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.190.132:8761/eureka/ #,http://192.168.190.132:8861/eureka/,http://192.168.190.132:8961/eureka/
