spring:
  application:
    name: jiang-eureka
  boot:
    admin:
      client:
        url: http://104.199.166.17:8084
  zipkin:
    base-url: http://104.199.166.17:9411

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
#    false为单机版，true为集群版
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://104.199.166.17:8761/eureka/,http://104.199.166.17:8861/eureka/,http://104.199.166.17:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info