spring:
  application:
    name: jiang-eureka
  boot:
    admin:
      client:
        url: http://35.241.113.30:8084
  zipkin:
    base-url: http://35.241.113.30:9411

server:
  port: 8761

eureka:
  instance:
    hostname: 35.241.113.30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info