spring:
  application:
    name: jiang-eureka
  boot:
    admin:
      client:
        url: http://35.241.113.30:8084
  zipkin:
    base-url: http://35.241.113.30:9411

server:
  port: 8761

eureka:
  instance:
    hostname: 35.241.113.30
  client:
#    false为单机版，true为集群版
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://35.241.113.30:8761/eureka/,http://35.241.113.30:8861/eureka/,http://35.241.113.30:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info